### ISSUE TITLE
TPM not detected

### ISSUE THREAD

**Issue by Vichingo455** [orangegrouptech/KnowMySystem#1]
I got the same issue in Windows 11 Compatibility Checker, TPM 2.0 is not detected and I have it:

![Immagine 2022-04-01 152257](https://user-images.githubusercontent.com/59311016/161272340-ec836eed-b988-4d85-9238-06449f95faee.jpg)

Any fix @orangegrouptech ?

**Comment by orangegrouptech** [comment]
After investigating, it seems like the version of wmic I packaged with the app is outdated and will not produce a result in Windows 11. Rolling out a fix now

**Comment by orangegrouptech** [comment]
Check out Patch 1.3 and see if it fixes it: https://github.com/orangegrouptech/KnowMySystem/releases/tag/1.3

**Comment by Vichingo455** [comment]
Thanks, now it's fixed
